exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
    "**/scripts",
]
source_roots = ["."]

[[modules]]
path = "floorcast.common"
depends_on = []

[[modules]]
path = "floorcast.domain"
depends_on = []

[[modules]]
path = "floorcast.infrastructure"
depends_on = []

[[modules]]
path = "floorcast.adapters"
depends_on = ["floorcast.domain"]

[[modules]]
path = "floorcast.services"
depends_on = ["floorcast.domain"]

[[modules]]
path = "floorcast.repositories"
depends_on = ["floorcast.domain"]

[[modules]]
path = "floorcast.api"
depends_on = ["floorcast.domain", "floorcast.services", "floorcast.common"]

[[modules]]
path = "floorcast.server"
depends_on = []

[[modules]]
path = "main"
depends_on = [
    "floorcast.adapters",
    "floorcast.api",
    "floorcast.domain",
    "floorcast.infrastructure",
    "floorcast.repositories",
    "floorcast.services",
    "floorcast.server",
]
